<?php

function media_imagezoom_menu()
{
	$items['media/tms/1.0.0/%/%/%/%'] = array(
		'page callback' => '_media_imagezoom_tile',
		'page arguments' => array(3,4,5,6),
		'type' => MENU_CALLBACK,
		'access arguments' => array('access content'),
	);
	return $items;
}

function _media_imagezoom_generate_zoomlevel_tiles($fid, $zoom_level)
{
	$media = file_load($fid);

	if ($media->type != 'image') {
		return;
	}

	$image = image_load($media->uri);
	$pow2 = pow(2.0,$zoom_level);
	$full_tile_width = max($image->info['width'],$image->info['height']) / pow(2.0,$zoom_level);
	
	// squarify
	image_crop($image, 0,0, max($image->info['width'],$image->info['height']), max($image->info['width'],$image->info['height']), TRUE );
	image_resize($image, 256*$pow2, 256*$pow2);

	// save temp
	//@file_delete(drupal_realpath('public://tiles/tmpResizedForCutting.jpg'), TRUE);
	image_save($image, 'public://tiles/tmpResizedForCutting.jpg');
	
	for ($x = 0; $x < $pow2; ++$x)
	for ($y = 0; $y < $pow2; ++$y)
	{
		
		$tile_name = 'public://tiles/tms/1.0.0/' . $fid . '/' . $zoom_level . '/' . $x . '/' . $y . '.jpg';

		$tile_cut = image_load('public://tiles/tmpResizedForCutting.jpg');

		image_crop($tile_cut, $x*256, ($pow2-$y-1)*256, 256, 256);
		@drupal_mkdir(dirname($tile_name), NULL, TRUE, NULL);

		//$image->source = $tile_name;
		image_save($tile_cut, $tile_name);
	}

}

function _media_imagezoom_tile($fid, $zoom_level, $x, $y)
{
	$y = intval(str_replace('.jpg', '', $y));

	//return implode(array($fid,$zoom_level,$x,$y), ' - ');


	$tile_name = 'public://tiles/tms/1.0.0/' . $fid . '/' . $zoom_level . '/' . $x . '/' . $y . '.jpg';

	// check if tile has already been created
	watchdog('media_imagezoom', 'checking for tile at ' . $tile_name);

	if (file_exists($tile_name))
	{
		watchdog('media_imagezoom', 'Serving cached tile ' . $tile_name);

		if (function_exists('drush_main')) {
			return;
		}
		drupal_goto(file_create_url($tile_name));
	}

	$media = file_load($fid);

	if ($media->type == 'image')
	{
		$image = image_load($media->uri);
		$full_tile_width = max($image->info['width'],$image->info['height']) / pow(2.0,$zoom_level);
		
		/*if ($image->info['width'] < $full_tile_width)
			image_crop($image, $full_tile_width, $full_tile_width);*/
		// squarify
		image_crop($image, 0,0, max($image->info['width'],$image->info['height']), max($image->info['width'],$image->info['height']), TRUE );
		/*image_resize($image, 256*pow(2,$zoom_level), 256*pow(2,$zoom_level));
		image_crop($image, 256*$x, 256*(pow(2,$zoom_level)-1),256,256);*/
		image_crop($image, $x*$full_tile_width, $image->info['height']-($y+1)*$full_tile_width, $full_tile_width-1, $full_tile_width-1);
		image_resize($image, 256, 256);
		@drupal_mkdir(dirname($tile_name), NULL, TRUE, NULL);

		//$image->source = $tile_name;
		image_save($image, $tile_name);
		if (function_exists('drush_main')) {
			return;
		}
		drupal_goto(file_create_url($tile_name));
	}

	drupal_set_message('Cannot tile non-image media');
	return print_r($media,true);
}

// ripped from media.browser.inc - media_browser_list
function media_imagezoom_getimages() {
  //TODO: temporary just to test iterating media items

  $params = drupal_get_query_parameters();
  // How do we validate these?  I don't know.
  // I think PDO should protect them, but I'm not 100% certain.
  module_load_include('inc', 'media', 'includes/media.browser');
  array_walk_recursive($params, '_media_recursive_check_plain');

  $types = isset($params['types']) ? $params['types'] : NULL;
  $url_include_patterns = isset($params['url_include_patterns']) ? $params['url_include_patterns'] : NULL;
  $url_exclude_patterns = isset($params['url_exclude_patterns']) ? $params['url_exclude_patterns'] : NULL;

  $start = isset($params['start']) ? $params['start'] : 0;
  $limit = isset($params['limit']) ? $params['limit'] : media_variable_get('browser_pager_limit');

  $query = db_select('file_managed', 'f');
  $query->fields('f', array('fid'));
  //$query->range($start, $limit);
  $query->orderBy('f.timestamp', 'DESC');

  // Add conditions based on file type *or* allowed extensions.
  $condition = $query;
  if (!empty($types) && !empty($params['file_extensions'])) {
    $condition = db_or();
  }
  if (!empty($types)) {
    $condition->condition('f.type', $types, 'IN');
  }
  if (!empty($params['file_extensions'])) {
    $extensions = array_filter(explode(' ', $params['file_extensions']));
    foreach ($extensions as $extension) {
      $condition->condition('f.uri', '%' . db_like('.' . $extension), 'LIKE');
    }
  }
  if ($condition instanceof DatabaseCondition) {
    $query->condition($condition);
  }

  if ($url_include_patterns) {
    $query->condition('f.uri', '%' . db_like($url_include_patterns) . '%', 'LIKE');
    // Insert stream related restrictions here.
  }
  if ($url_exclude_patterns) {
    $query->condition('f.uri', '%' . db_like($url_exclude_patterns) . '%', 'NOT LIKE');
  }

  // @todo Implement granular editorial access: http://drupal.org/node/696970.
  //   In the meantime, protect information about private files from being
  //   discovered by unprivileged users. See also media_view_page().
  if (!user_access('administer media')) {
    $query->condition('f.uri', db_like('private://') . '%', 'NOT LIKE');
  }

  $query->condition('f.status', FILE_STATUS_PERMANENT);

  foreach (array_keys(media_get_hidden_stream_wrappers()) as $name) {
    $query->condition('f.uri', db_like($name . '://') . '%', 'NOT LIKE');
  }

  $fids = $query->execute()->fetchCol();
  $files = file_load_multiple($fids);

  $images = array();
  foreach ($files as $file) {
    if ($file->type === 'image')
      $images[] = $file;
  }

  return $images;
}

/**
 * Implements hook_openlayers_layers().
 */
function media_imagezoom_openlayers_layers()
{
  $items = array();
  foreach (media_imagezoom_getimages() as $image)
  {
    // expose image as both base layer and overlay
    $items = array_merge($items, media_imagezoom_build_layer($image, TRUE) );
    $items = array_merge($items, media_imagezoom_build_layer($image) );
  }
  dpm('total media_imagezoom image count: ' . count($items));
  return $items;
}

function media_imagezoom_build_layer($image_file, $base_layer = FALSE)
{
  $items = array();
  $openlayers_layers = new stdClass;
  $openlayers_layers->disabled = FALSE; /* Edit this to true to make a default openlayers_layers disabled initially */
  $openlayers_layers->api_version = 1;
  $openlayers_layers->name = ($base_layer?'base_':'') . 'media_imagezoom_' . $image_file->fid;
  $openlayers_layers->title = $image_file->filename;
  $openlayers_layers->description = 'Media Image Zoom' . ($base_layer?' base':'') . ' layer of image ' . $image_file->filename;
  $openlayers_layers->data = array(
    'baselayer' => $base_layer,
    'base_url' => base_path() . 'sites/default/files/tiles/tms/',
    'layername' => $image_file->fid,
    'type' => 'jpg',
    'transparent' => TRUE,
    'resolutions' => array(
      0 => 156543.0339,
      1 => 78271.51695,
      2 => 39135.758475,
      3 => 19567.8792375,
      4 => 9783.93961875,
      5 => 4891.969809375,
      /*6 => 2445.9849046875,
      7 => 1222.9924523438,
      8 => 611.49622617188,
      9 => 305.74811308594,
      10 => 152.87405654297,
      11 => 76.437028271484,
      12 => 38.218514135742,
      13 => 19.109257067871,
      14 => 9.5546285339355,
      15 => 4.7773142669678,
      16 => 2.3886571334839,
      17 => 1.1943285667419,
      18 => 0.59716428337097,*/
    ),
    'params' => array(
      'isBaseLayer' => $base_layer,
      'layers' => 'media_imagezoom_' . $image_file->fid,
      'opacity' => 0.5,
    ),
    'params' => array(
      'isBaseLayer' => TRUE,
      'layers' => 'media_imagezoom_' . $image_file->fid,
      'opacity' => 0.5,
    ),
    'wrapDateLine' => 0,
    'layer_type' => 'openlayers_layer_type_tms',
  );
  $items[(($base_layer)?"base_":"") . "media_imagezoom_" . $image_file->fid] = $openlayers_layers;
  return $items;
}

/**
 * Implementation of hook_openlayers_presets().
 */
function media_imagezoom_openlayers_presets() {
  $presets = array();

  $imagezoom_map = array(
    'projection' => '4326',
    'width' => 'auto',
    'default_layer' => 'openlayers_default_wms',
    'height' => '300px',
    'center' => array(
      'lat' => '0',
      'lon' => '0',
      'zoom' => '2',
    ),
    'options' => array(
      'displayProjection' => '4326',
    ),
    'controls' => array(
      'LayerSwitcher' => TRUE,
      'Navigation' => TRUE,
      'PanZoomBar' => TRUE,
      'MousePosition' => TRUE,
    ),
  );

  $presets['media_imagezoom_map'] = array(
    'preset_name' => 'media_imagezoom_map',
    'preset_title' => t('Media Image-zoom Map'),
    'preset_description' => t('Provides OpenLayers view of large images'),
    'preset_data' => $imagezoom_map,
  );

  return $presets;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function media_imagezoom_ctools_plugin_api($module, $api) {
  // Define plugins for OpenLayers plugins api
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_layers':
        return array('version' => 1);

    }
  }
}

/**
 * Implements hook_views_api().
 */
function openlayers_test_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function media_imagezoom_field_formatter_info() {
  $formatters = array();
  $formatters['media_imagezoom_image'] = array(
    'label' => t('OpenLayers deep-image zoom'),
    'field types' => array('file', 'image'),
    'settings' => array(),
  );
  return $formatters;
} 

/**
 * Implements hook_file_formatter_view().
 */
function media_imagezoom_file_formatter_info() {
  // TODO: see if adding settings here will make a difference, maybe specify 'file type'
}


/**
 * Implements hook_field_formatter_view().
 */
function media_imagezoom_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $settings = $display['settings'];
  $element = array();
  foreach ($items as $delta => $item) {
    if ($field['type'] == 'image'
      && $item['image_dimensions']['width'] > 1920
      && $item['image_dimensions']['height'] > 1920) {
      $element[$delta] = array(
        '#theme' => 'imagezoom_openlayers',
        '#file' => $item,
      );
    }
  }
  return $element;
}

/**
 * Implements hook_theme().
 */
function media_imagezoom_theme($existing, $type, $theme, $path) {
  return array(
    'imagezoom_openlayers' => array(
      'function' => 'theme_media_imagezoom_formatter_imagezoom_openlayers',
      'render element' => 'element',
    ),
  );
}

function theme_media_imagezoom_formatter_imagezoom_openlayers($element) {
  dpm($element);

  $map = new stdClass;
  $map->disabled = FALSE; // Edit this to true to make a default map disabled initially
  $map->api_version = 1;
  $map->name = 'media_imagezoom_' . $element['element']['#file']['fid'];
  $map->title = 'Media Image Zoom - ' . $element['element']['#file']['filename'];
  $map->description = 'blah blah';
  $map->data = array(
    'width' => 'auto',
    'height' => '1000px',
    'image_path' => 'sites/all/modules/openlayers/themes/default_dark/img/',
    'css_path' => 'sites/all/modules/openlayers/themes/default_dark/style.css',
    'proxy_host' => '',
    'hide_empty_map' => 0,
    'center' => array(
      'initial' => array(
        'centerpoint' => '0, 0',
        'zoom' => '2',
      ),
      'restrict' => array(
        'restrictextent' => 0,
        'restrictedExtent' => '',
      ),
    ),
    'behaviors' => array(
      'openlayers_behavior_keyboarddefaults' => array(),
      'openlayers_behavior_attribution' => array(
        'seperator' => '',
      ),
      'openlayers_behavior_navigation' => array(
        'zoomWheelEnabled' => 1,
        'zoomBoxEnabled' => 1,
        'documentDrag' => 0,
      ),
      'openlayers_behavior_panzoombar' => array(
        'zoomWorldIcon' => 0,
        'panIcons' => 1,
      ),
    ),
    'default_layer' => $map->name,
    'layers' => array(
      $map->name => $map->name,
    ),
    'layer_weight' => array(
      $map->name => '0',
    ),
    'layer_styles' => array(
      $map->name => '0',
    ),
    'layer_styles_select' => array(
      $map->name => '0',
    ),
    'layer_activated' => array(
      $map->name => 0,
    ),
    'layer_switcher' => array(
      $map->name => 0,
    ),
    'projection' => '900913',
    'displayProjection' => '4326',
    'styles' => array(
      'default' => 'default',
      'select' => 'default_select',
      'temporary' => 'default',
    ),
    'map_name' => $map->name,
  );

  return openlayers_render_map($map);
}

